<img src="dot_1.png" />
<img src="dot_2.png" />
<img src="dot_3.gif" />

when the dot product between two different vectors is zero, they are orthogonal to each other

The dot product tells you what amount of one vector goes in the direction of another. 

https://developers.google.com/machine-learning/clustering/similarity/measuring-similarity

<img src="cs_1.png" width=800 />

Suppose we have a document with the word “sky” appearing 200 times and another document with the word “sky” appearing 50, the Euclidean distance between them will be higher but the angle will still be small because they are pointing to the same direction, which is what matters when we are comparing documents.

<img src="cs_2.png" />
<img src="cs_3.png" />
<img src="cs_5.png" />
<img src="cs_6.png" />

In [66]:
documents = (
"The sky is blue",
"The sky is blue and orange.",
"The sun is bright",
"The sun in the sky is bright",
"We can see the shining sun, the bright sun"
)

Instantiate the Sklearn TF-IDF Vectorizer and transform our documents into the TF-IDF matrix:

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)
print (tfidf_matrix.shape)

(5, 13)


<img src="vector_space_sentence.png" width=500 />

In [68]:
tfidf_matrix.toarray()[0]

array([0.        , 0.62925477, 0.        , 0.        , 0.        ,
       0.43940744, 0.        , 0.        , 0.        , 0.5223383 ,
       0.        , 0.371648  , 0.        ])

In [69]:
tfidf_matrix.toarray()[3]

array([0.        , 0.        , 0.35439091, 0.        , 0.52916939,
       0.2981248 , 0.        , 0.        , 0.        , 0.35439091,
       0.35439091, 0.5043041 , 0.        ])

In [65]:
tfidf_matrix.toarray()[4]

array([0.        , 0.        , 0.25044398, 0.37395793, 0.        ,
       0.        , 0.        , 0.37395793, 0.37395793, 0.        ,
       0.50088797, 0.35638591, 0.37395793])

In [77]:
tfidf_matrix[1:2].toarray()

array([[0.52386278, 0.4226492 , 0.        , 0.        , 0.        ,
        0.29513516, 0.52386278, 0.        , 0.        , 0.35083701,
        0.        , 0.24962342, 0.        ]])

In [98]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity( tfidf_matrix[3] # 4th Sentence
                  ,  tfidf_matrix # All 5 sentences
                 )

array([[0.50353381, 0.33820667, 0.73540545, 1.        , 0.44599209]])

In [72]:
import math
# This was already calculated on the previous step, so we just use the value
cos_sim = 0.50353381
angle_in_radians = math.acos(cos_sim)
print (math.degrees(angle_in_radians))

59.765928313667956


# Difference between Dot Product and Multiply

In [101]:
import math

In [111]:
import numpy.matlib 
import numpy as np 

a = np.array([0,2]) 
b = np.array([5,0]) 
np.dot(a,b)

0

In [112]:
np.multiply(a,b)

array([0, 0])