<img src="pca.svg" />

# Matrix Decomposition

## LU Decomposition

In [9]:
# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
P, L, U = lu(A)
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## QR Decomposition

### Complete

In [15]:
# QR decomposition
from numpy import array
from numpy.linalg import qr
# define rectangular matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A.shape)
print(A)
# factorize
Q, R = qr(A, 'complete')
print("-------")
print(Q.shape)
print(Q)
print("-------")
print(R.shape)
print(R)
# reconstruct
B = Q.dot(R)
print("-------")
print(B.shape)
print(B)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
-------
(3, 3)
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
-------
(3, 2)
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
-------
(3, 2)
[[1. 2.]
 [3. 4.]
 [5. 6.]]


### Reduced

In [14]:
# QR decomposition
from numpy import array
from numpy.linalg import qr
# define rectangular matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A.shape)
print(A)
# factorize
Q, R = qr(A, 'reduced')
print("-------")
print(Q.shape)
print(Q)
print("-------")
print(R.shape)
print(R)
# reconstruct
B = Q.dot(R)
print("-------")
print(B.shape)
print(B)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
-------
(3, 2)
[[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]
-------
(2, 2)
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]
-------
(3, 2)
[[1. 2.]
 [3. 4.]
 [5. 6.]]


## Cholesky decomposition

In [17]:
# Cholesky decomposition
from numpy import array
from numpy.linalg import cholesky
# define symmetrical matrix
A = array([
[2, 1, 1],
[1, 2, 1],
[1, 1, 2]])
print(A)
# factorize
L = cholesky(A)
print(L)
# reconstruct
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


# Eigendecomposition

In [81]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
print(values.shape)
print(values)
print(vectors.shape)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3,)
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
(3, 3)
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


The eigenvectors are returned as a matrix with the same dimensions as the parent matrix,
where each column is an eigenvector

In [82]:
# confirm first eigenvector
B = A.dot(vectors[:, 0])
print(B)
C = np.array(values[0]).dot(vectors[:, 0])
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [49]:
# confirm second eigenvector
B = A.dot(vectors[:, 1])
print(B)
C = np.array(values[1]).dot(vectors[:, 1])
print(C)

[ 0.87764976  0.09688771 -0.68387434]
[ 0.87764976  0.09688771 -0.68387434]


In [60]:
# reconstruct matrix
from numpy import diag
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
# create matrix from eigenvectors
print('Eigenvalues : ')
print(values)
Q = vectors
print('Eigenvectors Q: ')
print(Q)
# create inverse of eigenvectors matrix
R = inv(Q)
print('Eigenvectors Inverse R: ')
print(R)
# create diagonal matrix from eigenvalues
L = diag(values)
print('diagonal matrix from eigenvalues L: ')
print(L)
# reconstruct the original matrix
print('Reconstructed Original Matrix Q.dot(L).dot(R) : ')
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Eigenvalues : 
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectors Q: 
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
Eigenvectors Inverse R: 
[[-0.48295226 -0.59340999 -0.70386772]
 [-0.91788599 -0.24901003  0.41986593]
 [ 0.40824829 -0.81649658  0.40824829]]
diagonal matrix from eigenvalues L: 
[[ 1.61168440e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.11684397e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.30367773e-15]]
Reconstructed Original Matrix Q.dot(L).dot(R) : 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [85]:
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [86]:
A.sum()

45

In [87]:
sum(A)

array([12, 15, 18])

In [63]:
sum(A)

array([12, 15, 18])

In [88]:
np.mean(A)

5.0

In [71]:
M = np.mean(A, axis=0)
print(M)

[4. 5. 6.]


In [73]:
C = A - M
print(C)

[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


In [74]:
np.cov(C)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# PCA manually

In [79]:
# principal component analysis
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# column means
M = mean(A.T, axis=1)
# center columns by subtracting column means
C = A - M
# calculate covariance matrix of centered matrix
V = cov(C.T)
# factorize covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


# PCA Sklearn

In [80]:
# principal component analysis with scikit-learn
from numpy import array
from sklearn.decomposition import PCA
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# create the transform
pca = PCA(2)
# fit transform
pca.fit(A)
# access values and vectors
print(pca.components_)
print(pca.explained_variance_)
# transform data
B = pca.transform(A)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[8.000000e+00 4.118088e-34]
[[-2.82842712e+00 -4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  4.44089210e-16]]


# PCA with PIMA Dataset

In [8]:
# Feature Extraction with PCA
from pandas import read_csv
from sklearn.decomposition import PCA
# load data
filename = 'pima-indians-diabetes.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names, skiprows=1)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
# feature extraction
pca = PCA(n_components=3)
fit = pca.fit(X)
# summarize components
print("Explained Variance: %s" % fit.explained_variance_ratio_)
print(fit.components_)

Explained Variance: [0.88854663 0.06159078 0.02579012]
[[-2.02176587e-03  9.78115765e-02  1.60930503e-02  6.07566861e-02
   9.93110844e-01  1.40108085e-02  5.37167919e-04 -3.56474430e-03]
 [-2.26488861e-02 -9.72210040e-01 -1.41909330e-01  5.78614699e-02
   9.46266913e-02 -4.69729766e-02 -8.16804621e-04 -1.40168181e-01]
 [-2.24649003e-02  1.43428710e-01 -9.22467192e-01 -3.07013055e-01
   2.09773019e-02 -1.32444542e-01 -6.39983017e-04 -1.25454310e-01]]


<img src="Elephant1.jpg" />

<img src="Elephant2.jpg" />